"""Alembic script template for individual migrations."""

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = '369211c609d0'
down_revision = '1836c0af0ec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('target_company', sa.String(), nullable=False),
    sa.Column('interview_type', sa.String(), nullable=False),
    sa.Column('experience_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_profiles_id'), 'interview_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_interview_profiles_user_id'), 'interview_profiles', ['user_id'], unique=True)
    op.add_column('resumes', sa.Column('experience_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'experience_level')
    op.drop_index(op.f('ix_interview_profiles_user_id'), table_name='interview_profiles')
    op.drop_index(op.f('ix_interview_profiles_id'), table_name='interview_profiles')
    op.drop_table('interview_profiles')
    # ### end Alembic commands ###
